version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      TP4:
        ipv4_address: 172.59.0.2

  python_srv:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - '5000:5000'
    networks:
      TP4:
        ipv4_address: 172.59.0.3

volumes:
  mysql_data:

networks:
  TP4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.59.0.0/16
