name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python−version: ["3.8","3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python−version }}
      - name: Nom branch
        run: echo "${{ github.ref }}"
      - name: Nom repo
        run: echo "${{ github.repository }}"
      - name: Check OS Type
        run: echo "Current OS Type $(uname -s)"
      - name: python version
        run: echo $(python --version)
      - name: Install pytest
        run: pip3 install pytest
      - name: Run tests
        run: pytest TP1/test.py
