name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python−version: ["3.8", "3.10"]
    steps:
      - name: Set up Python for Demo
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Nom branch
        env:
          JOB_CONTEXT: ${{ github.ref }}
        run: echo "$JOB_CONTEXT"
      - name: Nom repo
        env:
          JOB_CONTEXT: ${{ github.repository }}
        run: echo "$JOB_CONTEXT"
      - name: Check OS Type
        run: |
          OS_TYPE=$(uname -s)
          echo "Current OS Type: $OS_TYPE"
      - uses: actions/checkout@v2
      - name: python version
        run: python --version
      - name: Install pytest
        run: pip3 install pytest
      - name: Run tests
        run: pytest TP1/test.py
